version: '2'
services:
  tc-cache:
    image: "redis:3.2.5"
    ports:
      - "6379:6379"
  tc-informix:
    image: "appiriodevops/tc-database-scripts:latest"
    hostname: informix.cloud.topcoder.com
    container_name: iif_innovator_c
    environment: 
      LICENSE: accept
    ports:
      - "2021:2021"
      - "2022:2022"
      - "27017:27017"
      - "27018:27018"
      - "27883:27883"
    tty: true
  tc-ldap:
    image: "appiriodevops/ldap"
    ports:
      - "389:389"
    tty: true

  tc-httpd:
    image: "tc-website:httpd"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${TC_PLATFORM_SRC_ROOT}:/root/tc-platform"
    tty: true
    links:
      - "run-tc-website:tc-website"
    depends_on:
      - "run-tc-website"
  
  build-tc-website:
    image: "tc-website:build"
    volumes:
      - "${TC_PLATFORM_SRC_ROOT}:/root/tc-platform"
      - "${DEPLOYMENT_DIR}:/root/deployment"

  run-tc-website:
    image: "tc-website:run"
    hostname: local.tc.cloud.topcoder.com
    volumes:
      - "${DEPLOYMENT_DIR}:/root/deployment"
    ports:
      - "8009:8009"
    extra_hosts:
      - "env.topcoder.com:172.16.100.1"
    depends_on:
      - "tc-informix"
      - "tc-ldap"
      - "tc-cache"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.100.0/24
        gateway: 172.16.100.1
