export ONLINE_REVIEW_SOURCE_ROOT=/Users/pvmagacho/Documents/Topcoder/Copilot/1_OnlineReview/tc-online-review
export ONLINE_REVIEW_DEPLOYMENT_DIR=/Users/pvmagacho/Documents/Topcoder/Copilot/1_OnlineReview/deployment
export DISABLE_ONLINE_REVIEW=0
export DISABLE_AUTO_PILOT=0
export DISABLE_LATE_DELIVERABLES_TRACKER=1
export DISABLE_REVIEW_ASSIGNMENT=1
