# .bashrc

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

alias jb="cd $JBOSS_HOME"
alias jbb="cd $JBOSS_HOME/bin"
alias jbd="cd $JBOSS_HOME/server/default/deploy"
alias jbl="cd $JBOSS_HOME/server/default/lib"
alias jbc="cd $JBOSS_HOME/server/default/conf"
alias tn="tail -f nohup.out"

echo jb="cd $JBOSS_HOME"
echo jbb="cd $JBOSS_HOME/bin"
echo jbd="cd $JBOSS_HOME/server/default/deploy"
echo jbl="cd $JBOSS_HOME/server/default/lib"
echo jbc="cd $JBOSS_HOME/server/default/conf"
echo tn="tail -f nohup.out"

export PATH
